namespace StoreManagement.Models;
public class Product { public int Id {get;set;} public string? Barcode {get;set;} public string Name {get;set;}=""; public string Category {get;set;}=""; public decimal PurchasePrice {get;set;} public decimal SalePrice {get;set;} public decimal StockQuantity {get;set;} public decimal MinimumStock {get;set;} public string? Supplier {get;set;} public string? ImagePath {get;set;} public string? Notes {get;set;} public DateTime CreatedAt {get;set;}=DateTime.Now; public DateTime UpdatedAt {get;set;}=DateTime.Now; public List<SaleItem> SaleItems {get;set;}=[]; }
public class Sale { public int Id {get;set;} public DateTime Date {get;set;}=DateTime.Now; public decimal Subtotal {get;set;} public decimal Discount {get;set;} public decimal Total {get;set;} public decimal PaidAmount {get;set;} public decimal ChangeAmount {get;set;} public decimal DebtAmount {get;set;} public string PaymentMethod {get;set;}="Nağd"; public string? CustomerName {get;set;} public bool IsReturned {get;set;} public List<SaleItem> Items {get;set;}=[]; }
public class SaleItem { public int Id {get;set;} public int SaleId {get;set;} public Sale? Sale {get;set;} public int ProductId {get;set;} public Product? Product {get;set;} public decimal Quantity {get;set;} public decimal SalePrice {get;set;} public decimal CostPrice {get;set;} public decimal Total {get;set;} public decimal Profit {get;set;} }
public class Purchase { public int Id {get;set;} public int ProductId {get;set;} public Product? Product {get;set;} public DateTime Date {get;set;}=DateTime.Now; public decimal Quantity {get;set;} public decimal PurchasePrice {get;set;} public string? Supplier {get;set;} public string? Notes {get;set;} public decimal Total => Quantity*PurchasePrice; }
public class Expense { public int Id {get;set;} public string Category {get;set;}="Digər"; public string Description {get;set;}=""; public decimal Amount {get;set;} public DateTime Date {get;set;}=DateTime.Now; public string? Notes {get;set;} }
public class Income { public int Id {get;set;} public string Category {get;set;}="Satış"; public string Description {get;set;}=""; public decimal Amount {get;set;} public DateTime Date {get;set;}=DateTime.Now; public string? Notes {get;set;} }
public class StockMovement { public int Id {get;set;} public int ProductId {get;set;} public string Type {get;set;}=""; public decimal Quantity {get;set;} public decimal PreviousStock {get;set;} public decimal NewStock {get;set;} public DateTime Date {get;set;}=DateTime.Now; public string? Notes {get;set;} }
public class Setting { public int Id {get;set;} public string StoreName {get;set;}="Calvotti Market"; public bool AllowNegativeStock {get;set;} }
public class Category { public int Id {get;set;} public string Name {get;set;}=""; }
public class Supplier { public int Id {get;set;} public string Name {get;set;}=""; public string? Phone {get;set;} public string? Notes {get;set;} }
